### PR TITLE
Adds an Annex and Recommendation about Multi-layer Tile Support

### PR DESCRIPTION
**Pull request by ghobona**
The new Recommendation states that the server is allowed to return a tile consisting of multiple layers. The Recommendation would go into Section 7.6.7 which describes a Response to a tile GET operation.

### CODE REVIEW

**Comment by jeffharrison** [comment]
Gobe,

The additions are well written, simple and understandable.

Thanks and Regards,
Jeff

**Comment by jerstlouis** [comment]
I had suggested that "layers or collections" be clarified with more accurate and precise language:

This draft specification does not impose any limits on the number of data layers that are included in a single tile.
The server is therefore allowed to return a tile consisting of multiple data layers, where each individual data layer, or the set of data layers as a whole, may correspond to a collection.

The intent of my suggestion was to:

- Clarify the meaning of "layer", which as demonstrated earlier is very often a source of confusion and push-back, primarily because of the confusion between the data and the presentation concept.
- Avoiding the confusion that having 'layers or collections' causes, which seems to imply that collections and layers are always entirely different things
- Recognizing that the multiple layers could be what corresponds to a collection, rather than the different layers, as implemented by GeoSolutions and Ecere in VTP2

We can review and decide in the meeting whether such changes, or similar ones addressing those concerns, should be applied.

**Comment by ghobona** [comment]
SWG decision on 2020-05-28

`/metadata` will be removed but a comment will be added to state that the `/metadata` was proven to work in VTP2.

**Comment by ghobona** [comment]
SWG decision on 2020-05-28 to use the text from @jerstlouis at https://github.com/opengeospatial/OGC-API-Tiles/pull/32#issuecomment-634047839

**Comment by jeffharrison** [comment]
Good clarification on this by @jerstlouis.

Best Regards,
Jeff

**Comment by ghobona** [comment]
Actions from SWG meeting of 2020-05-28 completed.

**Pull request merged**
